language: cpp

before_install:
  #new GCC
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  #new Clang
  - sudo add-apt-repository --yes ppa:h-rayflood/llvm
  #new CMake
  - sudo add-apt-repository --yes ppa:andykimpe/cmake 

  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq $SUPPORT
  - sudo apt-get install -qq $PACKAGE

  #setup compiler
  - export CC=${REAL_CC} CXX=${REAL_CXX}

before_script:
  - mkdir build
  - cd build
  - cmake ../fuzzylite

script:
  - make

env:
  - ignore=this

matrix:
  exclude:
    - env: ignore=this
  include:
    - compiler: clang
      env: REAL_CC=clang-3.2 REAL_CXX=clang++-3.2 PACKAGE=clang-3.2 SUPPORT=g++-4.8 
    - compiler: clang
      env: REAL_CC=clang-3.3 REAL_CXX=clang++-3.3 PACKAGE=clang-3.3 SUPPORT=g++-4.8 
    - compiler: clang
      env: REAL_CC=clang-3.4 REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=g++-4.8 
    - compiler: gcc 
      env: REAL_CC=gcc-4.7   REAL_CXX=g++-4.7     PACKAGE=g++-4.7   SUPPORT=
    - compiler: gcc
      env: REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=

notifications:
  email:
    recipients:
      - uzzylite.fail@mixaill.tk
    on_success: change
    on_failure: always
